### ISSUE TITLE
[FEAT] 

### ISSUE THREAD

**Issue by spidey0101** [sree-hari-s/MasteringPyTrail#10]
Hi, this is my first time working for an opensource project.Iam a newbie but I can try my best to help you out, can you assign any activity for me.

**Comment by sree-hari-s** [comment]
do you have any basic python project you have done.

**Comment by spidey0101** [comment]
Yes sir, I have made a python game but I face trouble to contribute it.Can you help me in it?

**Comment by spidey0101** [comment]
Sir I am facing trouble in contributing to your repository.I have forked ur
repo and done as you said but still it fails.
Can you help me with it?

**Comment by sree-hari-s** [comment]
can you specify the issue you are facing.

**Comment by spidey0101** [comment]
Iam using git bash to clone and add files after I execute the commit
command it shows fatal error can't find the repository but it is working
fine for others to whom I have contributed.
Please look into it.

**Comment by sree-hari-s** [comment]
can you please provide a screenshot

**Comment by sree-hari-s** [comment]
@spidey0101 is your issue resolved?
