### ISSUE TITLE
[DOCS] Documentation for all the Projects

### ISSUE THREAD

**Issue by sree-hari-s** [sree-hari-s/MasteringPyTrail#2]

**Comment by pranavdasan** [comment]
Which projects do you want commented, because many of them already have comments.

**Comment by ira-mane** [comment]
Hello , Could you please assign this issue to me .
I would love to work on documentation of of the projects in the repo .
Thankyou !!

**Comment by sree-hari-s** [comment]
> Which projects do you want commented, because many of them already have comments.

Its not about comments only, a Readme.md file in each folder so that any beginner could follow along

**Comment by sree-hari-s** [comment]
> Hello , Could you please assign this issue to me . I would love to work on documentation of of the projects in the repo . Thankyou !!

Yes I have assigned this to you do your best and make it as simple as  possible, I want it to be a beginner-friendly.

**Comment by sree-hari-s** [comment]
@ira-mane Hey are you working on this?

**Comment by ira-mane** [comment]
Yes, I am working on it.

**Comment by ira-mane** [comment]
Hello  @sree-hari-s can I create a new issue for the remaining projects documentation part and can you assign me that and close this issue ?

**Comment by ira-mane** [comment]
Thankyou so much ,I will do that right away and will complete all the docs by tomorrow.
