### ISSUE TITLE
[FEAT] Adding a beginner level project Rock-Paper-Scissors game

### ISSUE THREAD

**Issue by Soumya1219** [sree-hari-s/MasteringPyTrail#7]
**Is your feature request related to a problem? Please describe.**
I would like to add a beginner level project like Rock-Paper-Scissors game which includes working on loops and lists so that it will be good entry level experience to the beginners who are new to Python

**Describe the solution you'd like**
I already developed the project so I would like to add to this repository

**Describe alternatives you've considered**
We can even add that project to be implemented using OOPS also. 

**Additional context**
Kindly assign me with this issue. I would like contribute :)

**Comment by sree-hari-s** [comment]
@Soumya1219 status of your work?

**Comment by Soumya1219** [comment]
I will push the code by the EOD.

**Comment by sree-hari-s** [comment]
Thanks for letting me know

**Comment by Soumya1219** [comment]
Kindly tag it as #hacktober-accepted.
