### ISSUE TITLE
[DOCS] Addition of folders

### ISSUE THREAD

**Issue by Soumya1219** [sree-hari-s/MasteringPyTrail#8]
We can maintain the repository by adding the folders for each and every day from 1-100 and can name it as a python bootcamp which covers different type of topics every day and can include the technologies covered related to python in readme.md file. 
In readme.md file we can also add the sections like beginner, intermediate, advanced sections. 
And storing the existing folders like beginner hackerrank etc in seperate folder like Resources so that it will be true 100 days of code challenge. 

I would like to change the documentation and view of the repository.. 
Kindly assign me with this issue. I would like to contribute.. :)

**Comment by sree-hari-s** [comment]
Yes, that is a very good idea I also wanted to restructure the folder scheme for better readability.

**Comment by sree-hari-s** [comment]
I am closing this issue as there is no updates regarding this issue.
